lib/foist_web/router.ex
defmodule FoistWeb.Router do
  use FoistWeb, :router
  alias FoistWeb.PlayerRequired

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {FoistWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", FoistWeb do
    pipe_through :browser

    get "/", WelcomeController, :index
    get "/how_to_play", WelcomeController, :how_to_play
    live "/page", PageLive, :index
    get "/players/new", PlayerController, :new
    post "/players", PlayerController, :create

    scope "/", nil do
      pipe_through PlayerRequired

      get "/games", GameController, :index
      post "/games", GameController, :create
      get "/games/join", GameController, :join_code
      post "/games/join", GameController, :join
      live "/games/:join_code", GameLive, :show
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", FoistWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: FoistWeb.Telemetry
    end
  end
end

lib/foist/game.ex
defmodule Foist.Game do
  @moduledoc """
  Keeps track of game state.
  """
  alias Foist.{Hand, Player, Roster}

  @type t() :: %__MODULE__{
          card: Hand.card(),
          deck: [Hand.card()],
          hands: %{Player.t() => Hand.t()},
          roster: Roster.t(),
          tokens: non_neg_integer(),
          turn: 0..6,
          turn_order: tuple()
        }

  defstruct [:card, :deck, :hands, :roster, :tokens, :turn, :turn_order]

  @doc """
  Create a game for `roster` of players.
  """
  @spec new(Roster.t()) :: t()
  def new(roster = %Roster{players: players}) do
    [card | deck] = shuffle_deck()

    %__MODULE__{
      card: card,
      deck: deck,
      hands: divvy_tokens(players),
      roster: roster,
      tokens: 0,
      turn: 0,
      turn_order: players |> Enum.shuffle() |> List.to_tuple()
    }
  end

  @spec shuffle_deck() :: [Hand.card()]
  defp shuffle_deck do
    3..35
    |> Enum.shuffle()
    |> Enum.drop(9)
  end

  @spec divvy_tokens([Player.t()]) :: %{Player.t() => Hand.t()}
  defp divvy_tokens(players) do
    hand =
      case length(players) do
        size when size in 3..5 ->
          Hand.new(11)

        6 ->
          Hand.new(9)

        7 ->
          Hand.new(7)
      end

    Map.new(players, &{&1, hand})
  end

  @doc """
  As `player` place a token from hand on card.

  Fails if not `player`'s turn or if `player` out of tokens.
  """
  @spec place_token(t(), Player.t()) :: {:ok, t()} | :not_turn | :no_tokens
  def place_token(game = %__MODULE__{hands: hands, tokens: tokens}, player) do
    with :ok <- check_turn(game, player),
         {:ok, hand} <- Hand.remove_token(hands[player]) do
      game =
        %{game | tokens: tokens + 1}
        |> put_hand(player, hand)
        |> advance_turn()

      {:ok, game}
    end
  end

  @spec check_turn(t(), Player.t()) :: :ok | :not_turn
  defp check_turn(%__MODULE__{turn: turn, turn_order: turn_order}, player) do
    case elem(turn_order, turn) do
      ^player ->
        :ok

      _player ->
        :not_turn
    end
  end

  @spec put_hand(t(), Player.t(), Hand.t()) :: t()
  defp put_hand(game = %__MODULE__{hands: hands}, player, hand) do
    %{game | hands: %{hands | player => hand}}
  end

  @spec advance_turn(t()) :: t()
  defp advance_turn(game)

  defp advance_turn(game = %__MODULE__{turn: turn, turn_order: turn_order})
       when turn >= tuple_size(turn_order) - 1 do
    %{game | turn: 0}
  end

  defp advance_turn(game = %__MODULE__{turn: turn}) do
    %{game | turn: turn + 1}
  end

  @doc """
  As `player` rejoin `game`.

  Fails if `player` not on `game`'s roster.
  """
  @spec rejoin(t(), Player.t()) :: :ok | :error
  def rejoin(%__MODULE__{roster: roster}, player) do
    if Roster.member?(roster, player) do
      :ok
    else
      :error
    end
  end

  @doc """
  As `player` take the card.

  Fails if not `player`'s turn. Game ends when last card taken.
  """
  @spec take_card(t(), Player.t()) :: {:ok, t()} | {:done, %{Player.t() => Hand.t()}} | :not_turn
  def take_card(game = %__MODULE__{card: card, deck: deck, hands: hands, tokens: tokens}, player) do
    with :ok <- check_turn(game, player) do
      hand =
        hands[player]
        |> Hand.add_card(card)
        |> Hand.add_tokens(tokens)

      case deck do
        [card | deck] ->
          {:ok, put_hand(%{game | card: card, deck: deck, tokens: 0}, player, hand)}

        [] ->
          {:done, %{hands | player => hand}}
      end
    end
  end
end

lib/foist/games/hand.ex
defmodule Foist.Games.Hand do
  @moduledoc """
  A hand holds a player's cards and tokens.
  """

  @type card() :: 3..35
  @type t() :: %__MODULE__{cards: card(), tokens: non_neg_integer()}

  defstruct [:cards, :tokens]

  @doc """
  Add `card` to `hand`.
  """
  @spec add_card(t(), card()) :: t()
  def add_card(hand = %__MODULE__{cards: cards}, card) do
    %{hand | cards: Enum.sort([card | cards])}
  end

  @doc """
  Add `tokens` to `hand`.
  """
  @spec add_tokens(t(), non_neg_integer()) :: t()
  def add_tokens(hand = %__MODULE__{tokens: total}, tokens) do
    %{hand | tokens: total + tokens}
  end

  @doc """
  Create a hand.
  """
  @spec new(7 | 9 | 11) :: t()
  def new(tokens) do
    %__MODULE__{cards: [], tokens: tokens}
  end

  @doc """
  Remove a token from `hand` if there is one to take.
  """
  @spec remove_token(t()) :: {:ok, t()} | :no_tokens
  def remove_token(hand)

  def remove_token(%__MODULE__{tokens: 0}) do
    :no_tokens
  end

  def remove_token(hand = %__MODULE__{tokens: tokens}) do
    {:ok, %{hand | tokens: tokens - 1}}
  end

  @doc """
  Scores `hand`.

  Cards not in a run add to score. Tokens remove from score.
  """
  @spec score(t()) :: integer()
  def score(%__MODULE__{cards: cards, tokens: tokens}) do
    score_cards(cards, 0, -tokens)
  end

  @spec score_cards([card()], card() | 0, integer()) :: integer()
  defp score_cards(cards, previous, total)

  defp score_cards([], _previous, total) do
    total
  end

  defp score_cards([card | cards], previous, total) when card == previous + 1 do
    score_cards(cards, card, total)
  end

  defp score_cards([card | cards], _previous, total) do
    score_cards(cards, card, total + card)
  end
end

lib/foist_web/controllers/game_controller.ex
defmodule FoistWeb.GameController do
  use FoistWeb, :controller

  def create(conn, _params) do
    case Foist.create_game() do
      {:ok, join_code} ->
        redirect(conn, to: Routes.game_path(conn, :show, join_code))

      :error ->
        conn
        |> put_flash(:error, "Could not create game")
        |> redirect(to: Routes.game_path(conn, :index))
    end
  end

  def index(conn, _params) do
    player = get_session(conn, "player")

    render(conn, "index.html", page_title: "Play", player: player)
  end

  def join_code(conn, _params) do
    render(conn, "join.html", page_title: "Join Game", changeset: join_changeset(%{}))
  end

  def join(conn, %{"join_params" => params}) do
    changeset = join_changeset(params)

    case Ecto.Changeset.apply_action(changeset, :join) do
      {:ok, %{join_code: join_code}} ->
        redirect(conn, to: Routes.game_path(conn, :show, String.upcase(join_code)))

      {:error, changeset} ->
        render(conn, "join.html", page_title: "Join Game", changeset: changeset)
    end
  end

  defp join_changeset(attrs) do
    {%{}, %{join_code: :string}}
    |> Ecto.Changeset.cast(attrs, [:join_code])
    |> Ecto.Changeset.validate_required([:join_code])
    |> Ecto.Changeset.validate_length(:join_code, is: 4)
  end
end

lib/foist_web/live/game_live.ex
defmodule FoistWeb.GameLive do
  use FoistWeb, :live_view
  alias Foist.Events.{GameUpdated, LobbyUpdated, ScoreboardUpdated, TokensDivvied}
  alias FoistWeb.GameView

  @impl Phoenix.LiveView
  def handle_event(event, params, socket)

  def handle_event("leave_game", _params, socket) do
    %{join_code: join_code, player: player} = socket.assigns

    case Foist.leave_game(join_code, player) do
      :ok ->
        {:noreply, redirect(socket, to: Routes.game_path(socket, :index))}

      error when error in [:already_started, :not_owner, :not_enough_players] ->
        {:noreply, put_flash(socket, :error, error)}
    end
  end

  def handle_event("place_token", _params, socket) do
    %{join_code: join_code, player: player} = socket.assigns

    case Foist.place_token(join_code, player) do
      {:ok, tokens} ->
        {:noreply, assign(socket, tokens: tokens)}

      error when error in [:not_turn, :no_tokens] ->
        {:noreply, put_flash(socket, :error, error)}
    end
  end

  def handle_event("play_again", _params, socket) do
    %{join_code: join_code, player: player} = socket.assigns

    case Foist.play_again(join_code, player) do
      :ok ->
        {:noreply, socket}

      :not_scoreboard ->
        {:noreply, put_flash(socket, :error, :not_scoreboard)}
    end
  end

  def handle_event("start_game", _params, socket) do
    %{join_code: join_code, player: player} = socket.assigns

    case Foist.start_game(join_code, player) do
      :ok ->
        {:noreply, socket}

      error when error in [:already_started, :not_owner, :not_enough_players] ->
        {:noreply, put_flash(socket, :error, error)}
    end
  end

  def handle_event("take_card", _params, socket) do
    %{join_code: join_code, player: player} = socket.assigns

    case Foist.take_card(join_code, player) do
      {:ok, tokens} ->
        {:noreply, assign(socket, tokens: tokens)}

      :not_turn ->
        {:noreply, put_flash(socket, :error, :not_turn)}
    end
  end

  @impl Phoenix.LiveView
  def handle_info(message, socket)

  def handle_info(event = %GameUpdated{}, socket) do
    %GameUpdated{card: card, deck_size: deck_size, hands: hands, tokens: tokens, turn: turn} =
      event

    assigns = [
      card: card,
      card_tokens: tokens,
      deck_size: deck_size,
      hands: hands,
      screen: :game,
      turn: turn
    ]

    {:noreply, assign(socket, assigns)}
  end

  def handle_info(%LobbyUpdated{owner: owner, players: players}, socket) do
    assigns = [owner: owner, players: players, screen: :lobby]

    {:noreply, assign(socket, assigns)}
  end

  def handle_info(%ScoreboardUpdated{playing_again: playing_again, scores: scores}, socket) do
    {:noreply, assign(socket, playing_again: playing_again, scores: scores, screen: :scoreboard)}
  end

  def handle_info(%TokensDivvied{tokens: tokens}, socket) do
    {:noreply, assign(socket, tokens: tokens)}
  end

  @impl Phoenix.LiveView
  def mount(%{"join_code" => join_code}, %{"player" => player}, socket) do
    case Foist.join_game(join_code, player) do
      :ok ->
        {:ok, join_game(socket, join_code, player)}

      error when error in [:already_started, :full, :not_found] ->
        {:ok,
         socket
         |> put_flash(:error, error)
         |> redirect(to: Routes.game_path(socket, :join_code))}
    end
  end

  defp join_game(socket = %{host_uri: host}, join_code, player) do
    url =
      host
      |> struct!(authority: "localhost")
      |> URI.merge(Routes.game_path(socket, :show, join_code))
      |> URI.to_string()

    assigns = [
      card: nil,
      card_tokens: 0,
      deck_size: 0,
      hands: [],
      join_code: join_code,
      owner: nil,
      page_title: "Game #{join_code}",
      player: player,
      players: [],
      playing_again: [],
      screen: :lobby,
      scores: [],
      tokens: 0,
      turn: nil,
      url: url
    ]

    assign(socket, assigns)
  end

  @impl Phoenix.LiveView
  def render(assigns)

  def render(assigns = %{screen: :game}) do
    render(GameView, "game.html", assigns)
  end

  def render(assigns = %{screen: :lobby}) do
    render(GameView, "lobby.html", assigns)
  end

  def render(assigns = %{screen: :scoreboard}) do
    render(GameView, "scoreboard.html", assigns)
  end
end

lib/foist_web/views/game_view.ex
defmodule FoistWeb.GameView do
  use FoistWeb, :view
end

lib/foist_web/templates/game/game.html.leex
<ol class="text-xl">
  <%= for hand <- @hands do %>
    <%= if hand.turn? do %>
      <li class="bg-blue-200 flex px-2 py-0.5 rounded">
    <% else %>
      <li class="flex px-2 py-0.5 rounded">
    <% end %>
      <span class="flex-grow"><%= hand.name %></span>
      <ol class="flex flex-wrap">
        <%= for {card_type, card} <- hand.cards do %>
          <%= case card_type do %>
            <% :lone -> %>
              <li class="bg-blue-800 border border-blue-800 mx-0.5 px-0.5 rounded text-blue-200">
            <% :low -> %>
              <li class="bg-blue-800 border border-blue-800 ml-0.5 px-0.5 rounded-l text-blue-200">
            <% :mid -> %>
              <li class="border border-blue-800 px-0.5">
            <% :high -> %>
              <li class="border border-blue-800 mr-0.5 px-0.5 rounded-r">
          <% end %>
            <%= card %>
          </li>
        <% end %>
      </ol>
    </li>
  <% end %>
</ol>
<section class="flex flex-grow my-2">
  <ul class="flex items-center w-full">
    <li class="flex flex-col w-1/4">
      <label class="bg-blue-800 border border-blue-800 rounded-tl text-blue-200 text-center">Deck Size</label>
      <span class="border border-blue-800 rounded-bl text-center text-2xl"><%= @deck_size %></span>
    </li>
    <li class="flex flex-col w-1/2">
      <label class="bg-blue-800 border border-blue-800 flex flex-col rounded-t text-blue-200 text-center">Card</label>
      <span class="border border-blue-800 rounded-b text-center text-8xl"><%= @card %></span>
    </li>
    <li class="flex flex-col w-1/4">
      <label class="bg-blue-800 border border-blue-800 flex flex-col rounded-tr text-blue-200 text-center">Tokens</label>
      <span class="border border-blue-800 rounded-br text-center text-2xl"><%= @card_tokens %></span>
    </li>
  </ul>
</section>
<span class="text-center">My Tokens: <%= @tokens %></span>

<%= if @turn == @player and @tokens > 0 do %>
  <button class="bg-blue-800 border border-blue-800 my-2 p-2 rounded text-blue-200 w-full" phx-click="place_token">
<% else %>
  <button class="border border-blue-200 my-2 p-2 rounded text-blue-200 w-full" disabled>
<% end %>
  Place Token on Card
</button>

<%= if @turn == @player do %>
  <button class="bg-blue-200 border border-blue-800 my-2 p-2 rounded text-blue-800 w-full" phx-click="take_card">
<% else %>
  <button class="border border-blue-200 my-2 p-2 rounded text-blue-200 w-full" disabled>
<% end %>
 Take Card
</button>

lib/foist_web/templates/game/index.html.eex
<section class="flex flex-col flex-grow items-center">
  <h3>Playing As</h3>
  <%= link @player.name, to: Routes.player_path(@conn, :new, redirect: @conn.request_path), class: "text-3xl" %>
</section>
<%= link "Join Game", to: Routes.game_path(@conn, :join_code), class: "bg-blue-800 border border-blue-800 my-2 p-2 rounded text-blue-200 text-center w-full" %>
<%= link "Create Game", to: Routes.game_path(@conn, :create), method: "post", class: "bg-blue-200 border border-blue-800 my-2 p-2 rounded text-blue-800 text-center w-full" %>
<%= link "How to Play", to: Routes.welcome_path(@conn, :how_to_play), class: "bg-blue-200 border border-blue-800 my-2 p-2 rounded text-blue-800 text-center w-full" %>

lib/foist_web/templates/game/join.html.eex
<%= form_for @changeset, Routes.game_path(@conn, :join), [as: :join_params, class: "flex flex-col flex-grow"], fn f -> %>
  <%= label f, :join_code, class: "capitalize" %>
  <%= text_input f, :join_code, autocapitalize: "characters", maxlength: "4", placeholder: "Enter join code", class: "bg-blue-200 p-2 placeholder-blue-400 text-2xl uppercase" %>
  <%= error_tag f, :join_code %>

  <section class="flex-grow mt-2"></section>

  <%= submit "Play", class: "bg-blue-800 border border-blue-800 my-2 p-2 rounded text-blue-200 w-full" %>
  <%= link "Cancel", to: Routes.game_path(@conn, :index), class: "bg-blue-200 border border-blue-800 my-2 p-2 rounded text-blue-800 text-center w-full" %>
<% end %>

lib/foist_web/templates/game/lobby.html.leex
<section class="flex flex-col flex-grow items-center">
  <h3>Join Code</h3>
  <%= link @join_code, to: @url, class: "text-3xl" %>
  <p class="text-center text-xs w-6/12">Give your friends this join code, or it's also a link you can share directly to the game.</p>
  <h3 class="mt-2">Players (<%= length(@players) %>/7)</h3>
  <%= for player <- @players do %>
    <span class="text-2xl"><%= player.name %></span>
  <% end %>
</section>
<%= if @owner == @player and length(@players) >= 3 do %>
  <button class="bg-blue-800 border border-blue-800 my-2 p-2 rounded text-blue-200 w-full" phx-click="start_game">Start Game</button>
<% end %>
<button class="bg-blue-200 border border-blue-800 my-2 p-2 rounded text-blue-800 w-full" phx-click="leave_game">Leave Game</button>

lib/foist_web/templates/game/scoreboard.html.leex
<table class="w-full">
  <thead>
    <tr>
      <th colspan="2" class="font-normal text-center">Scores</th>
    </tr>
  </thead>
  <tbody class="text-2xl">
    <%= for player <- @scores do %>
      <tr>
        <%= if player.play_again == :no do %>
          <td class="line-through text-blue-200">
        <% else %>
          <td>
        <% end %>
          <%= player.name %>
          <%= if player.play_again == :yes do %>
            ✓
          <% end %>
        </td>
        <td class="text-right"><%= player.score %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="flex-grow"></div>
<%= if @player not in @playing_again do %>
  <button class="bg-blue-800 border border-blue-800 my-2 p-2 rounded text-blue-200 w-full" phx-click="play_again">Play Again</button>
<% end %>
<button class="bg-blue-200 border border-blue-800 my-2 p-2 rounded text-blue-800 w-full" phx-click="leave_game">Leave Game</button>